import Head from 'next/head'
import Image from 'next/image'
import {
  Box,
  useColorModeValue,
  Heading,
  VStack,
  Avatar,
  Divider,
  Flex,
  Spacer,
  Link,
} from '@chakra-ui/react'
import { motion } from 'framer-motion'
import Nav from '../components/Navbar'
import FadeIn from 'react-fade-in'

const MotionBox = motion(Box)
export default function Home() {
  return (
    <Box bg={useColorModeValue('orange.100', 'gray.900')}>
      <Nav />
      <Head>
        <title>Onyekachi Igwe </title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href='https://avatars.githubusercontent.com/u/75808489?v=4'
        />
      </Head>
      <Flex>
        <Spacer />
        <Box minHeight='80vh' mt='100'>
          <FadeIn transitionDuration={2000}>
            <VStack spacing='3vh'>
              <MotionBox whileHover={{ scale: 1.25 }}>
                <Avatar
                  borderColor='white'
                  borderWidth='4px'
                  size='2xl'
                  src='https://avatars.githubusercontent.com/u/75808489?v=4'
                />
              </MotionBox>
              <Box bgColor='blue.400' maxW='90vw' px='5' py='1' rounded='lg'>
                Hello, I am a student and backend developer based in the US!
              </Box>
              <Divider orientation='horizontal' size='lg' background='black' />
              <MotionBox whileHover={{ scale: 1.25 }}>
                <Heading py='50'>About</Heading>
              </MotionBox>
              <Box>
                <Heading
                  size='md'
                  my='2'
                  textAlign={'center'}
                  fontWeight='none'
                >
                  {' '}
                  🚀 I’m currently working on learning all things{' '}
                  <Link
                    href='https://sacks.substack.com/'
                    isExternal
                    color='red.200'
                  >
                    SaaS
                  </Link>
                  .
                </Heading>

                <Heading
                  size='md'
                  my='5'
                  textAlign={'center'}
                  fontWeight='none'
                >
                  💬 Talk to me about{' '}
                  <Link href='https://go.dev/' isExternal color='blue.200'>
                    Go
                  </Link>
                  ,{' '}
                  <Link
                    href='https://risingstars.js.org/2021/en'
                    isExternal
                    color='purple.200'
                  >
                    JavaScript
                  </Link>
                  ,{' '}
                  <Link
                    href=' https://www.indiehackers.com/'
                    isExternal
                    color='pink.200'
                  >
                    Entrepreneurship
                  </Link>
                </Heading>
                <Heading
                  size='md'
                  my='5'
                  textAlign={'center'}
                  fontWeight='none'
                >
                  {' '}
                  ✨ I’m currently learning Go and Microservices!
                </Heading>
                <Heading
                  size='md'
                  my='5'
                  textAlign={'center'}
                  fontWeight='none'
                >
                  🤔 I’m looking to work on anything.
                </Heading>
              </Box>
              <Divider />
              <MotionBox whileHover={{ scale: 1.25 }}>
                <Link href=' https://github.com/igweo' isExternal>
                  <Heading>Github</Heading>
                </Link>
              </MotionBox>
              <Link href=' https://github.com/igweo' isExternal>
                <MotionBox whileHover={{ scale: 1.25 }}>
                  <Avatar
                    borderColor='white'
                    borderWidth='4px'
                    bgColor='white'
                    size='2xl'
                    src='https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg'
                  />
                </MotionBox>
              </Link>
            </VStack>
          </FadeIn>
        </Box>
        <Spacer />
      </Flex>
    </Box>
  )
}
